# rename this file to shopify.config.yml
# and replace all placeholder values
# docs: https://shopify.github.io/themekit/configuration
development:
  password: [your-api-password]
  theme_id: "[your-theme-id]"
  store: [your-store].myshopify.com
  directory: shopify
  ignores:
    - .shopifyignore
production:
  password: [your-api-password]
  theme_id: "[your-theme-id]"
  store: [your-store].myshopify.com
  directory: shopify
  ignores:
    - .shopifyignore